version: '3.2'
services:
  weather-app1:
    build: ./weather-app
    tty: true
    networks:
     - frontend
  weather-app2:
    build: ./weather-app
    tty: true
    networks:
     - frontend
  weather-app3:
    build: ./weather-app
    tty: true
    networks:
     - frontend
  loadbalancer:
    build: ./load-balancer
    image: nginx
    tty: true
    ports:
     - '80:80'
    networks:
     - frontend

networks:
  frontend:
